### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by fengmk2** [alibaba-archive/mredis#1]
```
TypeError: Cannot read property 'get' of undefined
    at MultiRedis.get (/home/admin/index/target/index/node_modules/mredis/lib/multi_redis.js:128:11)
    at RedisStore.get (/home/admin/index/target/index/node_modules/connect-mredis/lib/connect-mredis.js:83:17)
    at Object.session [as handle] (/home/admin/index/target/index/node_modules/connect/lib/middleware/session.js:319:11)
    at next (/home/admin/index/target/index/node_modules/connect/lib/http.js:203:15)
    at Object.cookieParser [as handle] (/home/admin/index/target/index/node_modules/connect/lib/middleware/cookieParser.js:44:5)
    at next (/home/admin/index/target/index/node_modules/connect/lib/http.js:203:15)
    at Object.bodyParser [as handle] (/home/admin/index/target/index/node_modules/connect/lib/middleware/bodyParser.js:95:61)
    at next (/home/admin/index/target/index/node_modules/connect/lib/http.js:203:15)
    at Object.handle (/home/admin/index/target/index/lib/redirect.js:16:5)
    at next (/home/admin/index/target/index/node_modules/connect/lib/http.js:203:15)

```

**Comment by fengmk2** [comment]
重现方法：连接2个redis后，然后kill掉被选择的那个，就出现此bug了。修复此问题后，加上对应的单元测试吧。

**Comment by dead-horse** [comment]
了解
